-- Electrodomesticos - seed Neon (categories + produits)
CREATE TABLE IF NOT EXISTS categories (
  id TEXT PRIMARY KEY, name TEXT NOT NULL, type TEXT NOT NULL,
  iconKey TEXT NOT NULL, description TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
  id INTEGER PRIMARY KEY, name TEXT NOT NULL, slug TEXT UNIQUE NOT NULL,
  category TEXT NOT NULL REFERENCES categories(id),
  price DOUBLE PRECISION NOT NULL, oldPrice DOUBLE PRECISION, badge TEXT,
  rating DOUBLE PRECISION NOT NULL, reviews INTEGER NOT NULL,
  features JSONB NOT NULL, description TEXT NOT NULL, specs JSONB NOT NULL,
  image TEXT, images JSONB DEFAULT '[]'::jsonb, stock INTEGER NOT NULL DEFAULT 10,
  brand TEXT, gtin TEXT, mpn TEXT
);

-- Categories
INSERT INTO categories (id,name,type,iconKey,description) VALUES ('lave-linge','Lave-linge','GEM','lave-linge','Moteurs inverter, lavage économe, résultats constants') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id,name,type,iconKey,description) VALUES ('refrigerateur','Réfrigérateurs','GEM','refrigerateur','NoFrost, connectés, adaptés à chaque cuisine') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id,name,type,iconKey,description) VALUES ('lave-vaisselle','Lave-vaisselle','GEM','lave-vaisselle','Silencieux, programmes courts, efficacité sans compromis') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id,name,type,iconKey,description) VALUES ('four-plaque','Fours & Plaques','GEM','four-plaque','Pyrolyse, induction, cuisson professionnelle à la maison') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id,name,type,iconKey,description) VALUES ('micro-ondes','Micro-ondes','PEM','micro-ondes','Grill intégré, capteurs intelligents, résultats fiables') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id,name,type,iconKey,description) VALUES ('aspirateur','Aspirateurs & Robots','PEM','aspirateur','Sans fil, LiDAR, autonomes — sans effort') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id,name,type,iconKey,description) VALUES ('petit-cuisine','Petit Appareils Cuisine','PEM','petit-cuisine','Friteuses à air, multicuiseurs, appareils du quotidien') ON CONFLICT (id) DO NOTHING;

-- Produits (GTIN EAN-13 ES captures, stock, marque, MPN)
INSERT INTO products (id,name,slug,category,price,oldPrice,badge,rating,reviews,features,description,specs,image,images,stock,brand,gtin,mpn) VALUES
  (1,'Lave-linge Inverter Pro 9kg','lave-linge-inverter-pro-9kg','lave-linge',549.99,649.99,'bestseller',4.8,234,'["Moteur Inverter","Classe A+++","60×60cm","1200 tr/min","15 programmes"]'::jsonb,'Un lave-linge qui ne vous réveille pas. Le moteur inverter fonctionne sans charbon — moins de bruit, moins de consommation, plus de fiabilité. 40% d''économie par rapport aux modèles classiques, et les vêtements sortent toujours propres.','{"Capacité":"9 kg","Vitesse d''essorage":"1200 tr/min","Classe énergie":"A+++","Dimensions":"60 × 60 × 85 cm","Bruit lavage":"47 dB","Programmes":"15"}'::jsonb,NULL,'[]'::jsonb,10,'Electrodomésticos','8412345600012','LL-IP9KG'),
  (2,'Réfrigérateur Connecté NoFrost 360L','refrigerateur-connecte-nofrost-360l','refrigerateur',899.99,NULL,'new',4.9,187,'["NoFrost","Écran tactile","Suivi aliments","WiFi","Classe A++"]'::jsonb,'Un réfrigérateur qui vous rappelle d''acheter des œufs. L''écran tactile et l''application mobile suivent vos aliments en temps réel. Pas de givre, pas de mauvaises surprises. La température reste uniforme, partout.','{"Capacité totale":"360 L","Capacité congélateur":"95 L","Classe énergie":"A++","Dimensions":"60 × 65 × 185 cm","Connectivité":"WiFi / App","Technologie":"NoFrost Double Flux"}'::jsonb,NULL,'[]'::jsonb,8,'Electrodomésticos','8412345600029','RF-CN360'),
  (3,'Lave-vaisselle ECO Silence 60cm','lave-vaisselle-eco-silence-60cm','lave-vaisselle',429.99,499.99,'bestseller',4.7,156,'["Classe A++","44 dB","14 couverts","6 programmes","Séchage Naturel"]'::jsonb,'On oublie qu''il tourne. Le lave-vaisselle ECO Silence fonctionne à 44 dB — à peine le bruit d''une bibliothèque. Les programmes ECO consomment moins d''eau et d''énergie, sans sacrifier la vaisselle.','{"Capacité":"14 couverts","Classe énergie":"A++","Niveau sonore":"44 dB","Dimensions":"60 × 60 × 85 cm","Programmes":"6 + 3 express","Séchage":"Aérothermique"}'::jsonb,NULL,'[]'::jsonb,12,'Electrodomésticos','8412345600036','LD-ES60'),
  (4,'Four Encastrable Pyrolyse 71L','four-encastable-pyrolyse-71l','four-plaque',799.99,NULL,NULL,4.6,98,'["Pyrolyse","71 litres","Vapeur","Thermomètre","Classe A"]'::jsonb,'71 litres, ça fait de la place. La pyrolyse nettoie tout à haute température — il suffit d''essuyer à la fin. La fonction vapeur préserve les nutriments de vos plats. Un four pour ceux qui cuisinent vraiment.','{"Capacité":"71 L","Classe énergie":"A","Puissance":"3500 W","Fonctions":"8 + pyrolyse","Dimensions":"60 × 55 × 60 cm","Vapeur":"Oui"}'::jsonb,NULL,'[]'::jsonb,6,'Electrodomésticos','8412345600043','FO-PY71'),
  (5,'Micro-ondes Sensor Grill 25L','micro-ondes-sensor-grill-25l','micro-ondes',189.99,229.99,'eco',4.5,312,'["Capteur humidité","Grill 1000W","25 litres","Décongélation auto","Design compact"]'::jsonb,'Il sait quand c''est chaud. Le capteur humidité mesure l''état de vos aliments et ajuste la puissance automatiquement. Le grill à 1000W dore en quelques minutes. Pas de vaisselle à laver après.','{"Capacité":"25 L","Puissance micro-ondes":"900 W","Puissance grill":"1000 W","Programmes":"8 automatiques","Dimensions":"50 × 39 × 30 cm","Capteur":"Humidité"}'::jsonb,NULL,'[]'::jsonb,20,'Electrodomésticos','8412345600050','MO-SG25'),
  (6,'Robot Aspirateur LiDAR Navigate','robot-aspirateur-lidar-navigate','aspirateur',349.99,449.99,'bestseller',4.8,445,'["LiDAR","Autonomie 180 min","Lavage","App","Mappage 3D"]'::jsonb,'Il cartographie votre intérieur et aspire tout sans se tromper. La technologie LiDAR trace des routes précises. Aspiration + lavage en un seul passage. 180 minutes d''autonomie — même les grands appartements sont couverts.','{"Technologie":"LiDAR 3D","Autonomie":"180 min","Puissance aspiration":"4000 Pa","Capacité bac":"450 ml (poussière) / 270 ml (eau)","Connectivité":"WiFi / App / Alexa","Lavage":"Oui, 3 niveaux"}'::jsonb,NULL,'[]'::jsonb,15,'Electrodomésticos','8412345600067','RB-LD360'),
  (7,'Friteuse à Air Smart 5.5L','friteuse-air-smart-5-5l','petit-cuisine',79.99,109.99,'eco',4.7,678,'["80% moins de gras","10 programmes","5.5 litres","Écran tactile","Recirculation d''air"]'::jsonb,'Des frites croustillantes sans la graisse. La recirculation d''air chaud fait le travail — 80% de gras en moins. 10 programmes pour tout cuisiner, de la viande aux légumes. Le plus vendu de la catégorie, et c''est mérité.','{"Capacité":"5.5 L","Puissance":"1700 W","Plages de température":"40-200°C","Programmes":"10 automatiques","Écran":"Tactile LED","Dimensions":"33 × 33 × 38 cm"}'::jsonb,NULL,'[]'::jsonb,25,'Electrodomésticos','8412345600074','AF-SM55'),
  (8,'Plaque de Cuisson Induction Duo','plaque-cuisson-induction-duo','four-plaque',329.99,NULL,'new',4.4,89,'["Induction","2 feux","Boost 3700W","Minuterie","Verre céramique"]'::jsonb,'L''eau bout en quelques secondes. Le boost à 3700W accélère tout. Deux feux pour deux poêles en même temps. Surface en verre céramique — rayures résistantes, nettoyage en un coup.','{"Type":"Induction","Nombre de feux":"2","Puissance max":"3700 W (Boost)","Surface":"Verre céramique","Dimensions":"59 × 35 cm","Commandes":"Touche tactile"}'::jsonb,NULL,'[]'::jsonb,10,'Electrodomésticos','8412345600081','PL-ID2'),
  (9,'Aspirateur Sans Fil Pro 250W','aspirateur-sans-fil-pro-250w','aspirateur',279.99,NULL,NULL,4.6,203,'["250W","60 min autonomie","HEPA 13","Tête motorisée","Léger 2.8kg"]'::jsonb,'250W de puissance, 60 minutes d''autonomie, 2.8 kg à la main. Le filtre HEPA 13 capture 99.97% des particules — idéal si vous êtes allergique. La tête motorisée passe partout.','{"Puissance":"250 W","Autonomie":"60 min","Filtre":"HEPA 13","Poids":"2.8 kg","Capacité bac":"0.7 L","Charge":"3.5 heures"}'::jsonb,NULL,'[]'::jsonb,18,'Electrodomésticos','8412345600098','AS-PF250'),
  (10,'Multicuiseur 6L 14 en 1','multicuiseur-6l-14-en-1','petit-cuisine',119.99,149.99,'bestseller',4.9,521,'["14 fonctions","6 litres","Programmable","Mijoteuse","Yaourtière"]'::jsonb,'Quatorze appareils dans un seul. Ragoûts, riz, yaourts, desserts vapeur — tout y est. Programmable, on met les ingrédients le matin et le dîner est prêt le soir. Les 14 en 1, c''est pas du marketing. C''est la vie.','{"Capacité":"6 L","Puissance":"1000 W","Fonctions":"14","Programmes":"Préréglés + manuel","Cuisson":"Sous pression / Normale / Vapeur","Dimensions":"35 × 35 × 38 cm"}'::jsonb,NULL,'[]'::jsonb,22,'Electrodomésticos','8412345600104','MC-6L14')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, slug = EXCLUDED.slug, category = EXCLUDED.category,
  price = EXCLUDED.price, oldPrice = EXCLUDED.oldPrice, badge = EXCLUDED.badge,
  rating = EXCLUDED.rating, reviews = EXCLUDED.reviews, features = EXCLUDED.features,
  description = EXCLUDED.description, specs = EXCLUDED.specs, image = EXCLUDED.image,
  images = EXCLUDED.images, stock = EXCLUDED.stock,
  brand = EXCLUDED.brand, gtin = EXCLUDED.gtin, mpn = EXCLUDED.mpn;
